### ISSUE TITLE
JSONExample funktioniert mit cHash

### ISSUE THREAD

**Issue by X-Tender** [einpraegsam/training#2]
Ich wollte das JSON Beispiel in unsere Extension einbauen, funktioniert soweit, aber nicht wenn ich `requireCHashArgumentForActionArguments = 1` in der `setup.ts` setze.

Was müsste man zusätzlich noch machen damit es funktioniert?

Betrifft den "Group" Branch.

**Comment by einpraegsam** [comment]
Das stimmt. Wenn der cHash nicht mitgegeben wird, dann schlägt in T3 8 der Check fehl. Wenn man einen Link per JS zusammenbaut, dann hat man keine Möglichkeit den cHash mitzuschicken. Aus meiner Sicht ist das "Sauberste" ein eigenes Plugin für den (oder alle) AJAX-Request(s) zu bauen (z.B. Pi2) und dort den Check auszuschalten:
`plugin.tx_extkey_pi2.features.requireCHashArgumentForActionArguments = 0`

**Comment by X-Tender** [comment]
Alles klar. Vielen dank.

**Comment by einpraegsam** [comment]
Alternative: `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters'] = 'L, pk_campaign, pk_kwd, utm_source, utm_medium, utm_campaign, utm_term, utm_content,tx_extkey_pi1[myparameter]';`

**Comment by X-Tender** [comment]
Auch gut. So könnte es sogar noch besser sein.
```javascript
$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters'] .= ',tx_extkey_pi1[myparameter]';
```
So überschreibt man es nicht komplett 😄

**Comment by einpraegsam** [comment]
Klar, was dir besser gefällt! :D

**Comment by einpraegsam** [comment]
Gerade getestet und vermutlich die schönste Variante wenn man TypeNum und nicht eID nutzt:
```
suggestAjax = PAGE
suggestAjax {
    typeNum = 847857858
    config {
        additionalHeaders = Content-Type: application/json
        additionalHeaders.10.header = Content-Type: application/json
        no_cache = 1
        disableAllHeaderCode = 1
        disablePrefixComment = 1
        xhtml_cleaning = 0
        admPanel = 0
        debug = 0
    }

    10  = USER
    10 {
        userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
        extensionName = Employees
        pluginName = Pi1
        vendorName = In2code
        controller = Employee
        action = suggestAjax
        switchableControllerActions.Employee.1 = suggestAjax
        features.requireCHashArgumentForActionArguments = 0
    }
}
```
