### ISSUE TITLE
example caching framework

### ISSUE THREAD

**Issue by dkern** [einpraegsam/training#3]
Hatten wir das Beispiel mit dem Caching Framework nur theoretisch behandelt, oder hatten wir da auch was zu gemacht und nur nicht commited? Ich bin mir nicht mehr sicher, konnte aber in der `eno.de` Branch auch nichts finden ...

**Comment by einpraegsam** [comment]
Ich glaube, dass wir das nur in der Theorie besprochen hatten. Aber hierzu gibt es eine recht gute Doku von TYPO3: https://docs.typo3.org/typo3cms/CoreApiReference/ApiOverview/CachingFramework/Developer/Index.html
Viele Grüße aus Rosenheim

**Comment by dkern** [comment]
Alles gut, danke! 😉 Grüße
