### ISSUE TITLE
JSONExample, zugriff auf das gesamte repository?!

### ISSUE THREAD

**Issue by X-Tender** [einpraegsam/training#4]
Ich würde gerne in meiner jsonAction auf das . gesamte repository zugreifen um mir dann eine json zusammenbasteln wie ich es gerne möchte aber wenn ich das hier mach:

```
$persons = $this->personRepository->findAll();
var_dump($persons->toArray());
```
Dann bekomme ich ein leeres Array zurück.
Selbst wenn ich nur `$this->personRepository` ausgebe erhalte ich in dem fall `NULL`.
Ich dachte das wird mittels Dependecy Injection hinzugefügt. Oder wird das wegen dem ganzen JONS gedöns ausgehebelt 😄 
Was müsste ich dann in dem falle noch machen damit ich auf repositorys zugreifen kann.

**Comment by X-Tender** [comment]
OK, nachdem ich mein Kopf mal zum nachdenken gebracht habe war es auch recht logisch.
Da ich das ja über den numType aufrufe und nicht direkt über das Plugin weiß er ja nicht wo er nachgucken soll, nachdem ich das hinzugefügt habe gibt es dann.

```
$query = $this->personRepository->createQuery();
$querySettings = $query->getQuerySettings();
$querySettings->setRespectStoragePage(FALSE);
$this->personRepository->setDefaultQuerySettings($querySettings);
```

Praktisch wäre wenn ich die StorageID aus der settings typoscript auslesen könnte und da setzen würde.

**Comment by einpraegsam** [comment]
Ja, wenn du die Storage sowieso per TypoScript nutzt, dann kannst du den Settings-Teil einfach in deiner TypeNum wieder hereinkopieren.
```
plugin.tx_extension_pi1 {
  ...
  persistence.storagePid = 123
}
suggestAjax = PAGE
suggestAjax {
    typeNum = 847857858
    config {
        additionalHeaders = Content-Type: application/json
        additionalHeaders.10.header = Content-Type: application/json
        no_cache = 1
        disableAllHeaderCode = 1
        disablePrefixComment = 1
        xhtml_cleaning = 0
        admPanel = 0
        debug = 0
    }

    10  = USER
    10 {
        userFunc = TYPO3\CMS\Extbase\Core\Bootstrap->run
        extensionName = Employees
        pluginName = Pi1
        vendorName = In2code
        controller = Employee
        action = suggestAjax
        switchableControllerActions.Employee.1 = suggestAjax
        features.requireCHashArgumentForActionArguments = 0
        persistence < plugin.tx_extension_pi1.persistence
    }
}
```

**Comment by X-Tender** [comment]
Ah klasse. Danke. Das kann ich dan perfekt mit der settings TS verbinden.
