### ISSUE TITLE
detach() & removeAll() Problematiken

### ISSUE THREAD

**Issue by X-Tender** [einpraegsam/training#5]
Ich bin kürzlich in ein Problem gelaufen das mich Fuchst und ich im Internet keine Lösung gefunden habe.

Und zwar habe ich ein Model mit einer 1:n bzw. einer n:m releation zu anderen Models.
Bei beiden konnte ich das Problem feststellen das wenn ich removeAll() aufrufe, was im Grunde nur ein foreach schleife ist,
```php
public function removeAll(ObjectStorage $objectStorage)
{
    foreach ($objectStorage as $object) {
        $this->detach($object);
    }
}
```
er mir nicht alle löscht, sondern immer eins überspringt. 

Wenn man das anhand einem einfachem Array erklärt dann würde das so aussehen:
Ich habe ein Array `$arr = ['a','b','c','d'];`Sagen wir mal das Array wäre eine realtion von Model X auf Model Y. z.b. hat eine Person 4 Autos.

Wenn ich jetzt in dem person Model `$this->cars->removeAll($this->cars);` ausführe dann steht in dem Array danach `['b','d']` noch drin. So als würde er den Pointer nicht gescheit setzen nachdem er es gelöscht hat?!

Mache ich hier was Grundsätzlich falsch?!

**Comment by einpraegsam** [comment]
Hmm, es gibt im Persistence Repository doch schon eine removeAll():
```
public function removeAll()
{
    foreach ($this->findAll() as $object) {
        $this->remove($object);
    }
}
```

Was ist damit?

Alternativ dazu sollte auch ein
```
// Alle Relationen löschen
$hauptmodell->setUntermodelle(new ObjectStorage());
```
tun

**Comment by X-Tender** [comment]
Mir dem removeAll() im repository würde doch alle Personen löschen, oder nicht. Ich möchte ja nur die Relation entfernen und nicht die Einträge löschen.
Mit dem `new ObjectStorage` habe ich es jetzt auch gelöst aber die removeAll() Funktion im ObjectStorage müsste ja auch seine Aufgabe machen.

**Comment by einpraegsam** [comment]
Stimmt, Denkfehler von mir. Aber nicht wundern, wenn du den einen oder anderen Bug in Extbase findest. Irgendwann lernt man wie man mit Workarrounds zum Ziel kommt :)

**Comment by X-Tender** [comment]
Nur um das mal logisch abzuschließen. Im typo3 Slack channel hat Felix Althaus eine Erklärung für dieses Problem erläutert:
>Beides, sowohl `foreach` als auch `ObjectStorage->detach` verwenden den gleich internen Array-Pointer für das `storage`-Array in `ObjectStorage`. Anders gesagt "verrutscht" der Zeiger der `foreach`-Schleife durch den Zugriff von `detach`. Kann auch richtig schwer zu findende Bugs bescheren :slightly_smiling_face:
Eine Möglichkeit (falls das ObjectStorage nicht so riesig ist, dass es ein Speicherproblem wird), ist `foreach ($this->focusPoints->toArray() as $focuspoint) ...` oder auch `foreach(clone $this->focusPoints as $focuspoint) ...` hauptsache die Iteration rennt im Hintergrund über ein anderes Array…

**Comment by einpraegsam** [comment]
Danke für die Erklärung!
